# Generated by Django 3.0.8 on 2020-11-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_auto_20201129_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='wilaya',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pro.Wilaya'),
        ),
    ]
