# Generated by Django 3.0.8 on 2020-12-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_auto_20201216_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumal',
            name='commande',
            field=models.IntegerField(null=True),
        ),
    ]
